### ISSUE TITLE
Does not build on Ubuntu 18.10

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-PythonBindings#2]
On Ubuntu 18.10, cmake does not run through as it does not find the BOOST Python library. It seems, the component used in the find_package() call is wrong (for Ubuntu 18.10). It should be there:

find_package(Boost REQUIRED COMPONENTS python3)

Maybe this also works on older BOOST resp. Ubuntu versions?

**Comment by vargheseg** [comment]
9581ffbb5a526e6f10967d6bb57006ec1c481e4c solves this.
