### ISSUE TITLE
Implementation for uint32 missing?

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/DeviceAccess-PythonBindings#5]
I tried to read an uint32 value via a Backend. It seems like read always uses double accessors and read_raw uses int32 accessors. 
So I don't know how to access an uint32.

**Comment by vargheseg** [comment]
With the current api, return type of read is fixed to a numpy.float64 array; but converting to numpy.uint32 or int() in python, should not  lose precision.

**Comment by vargheseg** [comment]
read_raw does not run fixed point conversion on received 32 bit value and returns the bit sequence  as received.

**Comment by zenker** [comment]
OK I found out that it was a problem in my backend - it only returned int32 if the value read is an int32. Else an exception was thrown. But of course I can do the conversion in my backend and return an int32 even if the value read is an uint32.

**Comment by mhier** [comment]
Actually you have to. All backend must work with any supported user data type, unless the original data cannot be converted into it (e.g. original data is a string and user requests a numeric type). In particular you should always be able to use a string, e.g. if you don't know what you have and just want to display it.

**Comment by zenker** [comment]
Now I realised that I can read the uint32 without a problem. My backend reads the uint and provides the requested int32 by a conversion.
But when I want to write this process variable the python bindings only support writing of int32, float32/64. 
My backend can not do an automatic conversion from int32 to uint32, so it simply writes the int32, which is not allowed in my case, because an uint32 is to be used (in my case the  OPC-UA server complains).
Of course the backend could find out the target type and try to convert the given type to the target type, but that doesn't work in any case (how to convert -9 to uint...).

**Comment by mhier** [comment]
Your backend must be able to convert. As long as one only wants to deal with positive, not too large numbers, uint32 and int32 must be interchangeable. Otherwise your backend does not comply with DeviceAccess and you cannot blame the PythonBindings for this. Numbers which are outside the allowed range of the register (like -9 for an unsigned register) should be moved into the allowed rage (i.e. you will get 0 then). The Python bindings are always using double as the data type which cover the full range of both int32 and uint32, so there should be no issues.

You absolutely must not use raw transfer as a way out here, it's just plain wrong. Fix your backend and it should work with the Python bindings as well. The implementation might not be nice under the hood and needs rework, but the actual issue here seems to be in your backend.

**Comment by killenb** [comment]
I think you would actually profit from implementing you backend as a NumericAddressed backend. Like this you would get all this for free (incl. the map file parser), with the downside that the map file format must match. But I think the better approach would be to make the NumericAddressed backend flexible so it can handle different parsers.

That being said here is how to make your accessor compliant: You need two steps of conversion
1. Convert from raw/the transport layer to the "generic" representation on the CPU
2. Convert from the "generic" representation to any user data type.

The second step is mandatory. Have a look at the IEEE754_SingleConverter in DeviceAccess and see how it is done. There is a class RoundingRangeCheckingDataConverter in there which is what you need. There already is a ticket to factor this out in DeviceAccess, so you could do this and then re-use that class.
https://github.com/ChimeraTK/DeviceAccess/issues/39

**Comment by mhier** [comment]
What could also help: The SubdeviceBackend currently provides as a local class (i.e. in the cc file) a FixedPointConvertingDecorator. We could move that out there and make it available for everyone. Alternatively the TypeChangingDecorator could help, I think it's still part of the ControlSystemAdapter, but could easily be moved to DeviceAccess for general use as well. You can simply decorate your existing fixed-type accessor with one of these decorators if getRegisterAccessor() is called for the "wrong" type.

**Comment by killenb** [comment]
Wasn't there also a separate class called TypeChangingDecorator?

**Comment by vargheseg** [comment]
In principle, the bindings api should support user desired types. This is a feature to be put in with https://github.com/ChimeraTK/DeviceAccess-PythonBindings/issues/3
