### ISSUE TITLE
Empty documentation

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-PythonBindings#6]
The documentation on chimeratk.github.io is essentially empty.

**Comment by vargheseg** [comment]
Temporary workaround:
https://chimeratk.github.io/DeviceAccess-PythonBindings/01.02/index.html

**Comment by vargheseg** [comment]
Bugfix in chimeratk.github.io + 229818e80e5085d10eaca9d5a9dc2ae3b8c92e8a fixes this issue.
