### ISSUE TITLE
Improve the interface of read_sequences

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess-PythonBindings#7]
The default for the second parameter of "read_sequences" should be an empty string, not 'None'. Like this it is possible to use read_sequences with just one string and without specifying the registerPath variable name:

`d.read_sequences('/TEST/DMA')`
instead of `d.read_sequences(registerPath='/TEST/DMA')` or `d.read_sequences('/TEST/DMA','')`  or `d.read_sequences('','/TEST/DMA')`

**Comment by vaeng** [comment]
This is outdated and not an issue with the new bindings. We should probably close this?

**Comment by mhier** [comment]
yes
