### ISSUE TITLE
read_sequences uses float32 as data type

### ISSUE THREAD

**Issue by mbuechl** [ChimeraTK/DeviceAccess-PythonBindings#8]
The data type for read_sequences uses float32 as data type. This is not sufficient to store 32 bit integer, which makes it useless for some data transfers.

Solution: Make the data type selectable (with dtype=np.xxx, like numpy arrays), (with default = float64?). In the ideal case the correct type would be picked/estimated from the catalogue information, but could be overwritten by the user, but this would be an extra ticket.

**Comment by jirikral** [comment]
I arrived to identical observation. The conversion to numpy array of float32 reduces precision and makes the transport useless for signed/unsigned int. The ideal solution is to return numpy array of data type based on the map file definition (int32 for ints, float32 for non-integer precision). User should be able to override.

**Comment by killenb** [comment]
A quick fix is in place: Python bindings 01.04 change the data type to double, so the content of a 32 bit integer can be transported without precision loss.
This still is not a clean solution and will break with 64 bit integers. Hence this ticket stays valid : Do a proper implementation with selectable type.

**Comment by jirikral** [comment]
Hello, I confirm that the quick fix works well with 1.04 package.

**Comment by vaeng** [comment]
> Do a proper implementation with selectable type.
This has been fixed in the new bindings, you are now free to chose the type.
